<?php

/**
 * @file
 */

use Drupal\Core\Link;

/**
 * Prepares variables for separated link field templates.
 *
 * This template outputs a separate title and link.
 *
 * Default template: link-formatter-link-separate.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - title: (optional) A descriptive or alternate title for the link, which
 *     may be different than the actual link text.
 *   - url_title: The anchor text for the link.
 *   - url: A \Drupal\Core\Url object.
 */
function template_preprocess_link_formatter_link_separate(&$variables): void {
  $variables['link'] = Link::fromTextAndUrl($variables['url_title'], $variables['url'])->toString();
}

/**
 * Add the 'allowed_protocols' setting to all existing link fields.
 */
function link_post_update_add_allowed_protocols(&$sandbox): void {
  if (!isset($sandbox['current'])) {
    $sandbox['current'] = 0;
  }

  // Load all field configurations.
  $field_config_storage = \Drupal::entityTypeManager()->getStorage('field_config');
  $field_configs = $field_config_storage->loadMultiple();

  // Process all configurations in batches.
  $total = count($field_configs);
  foreach (array_slice($field_configs, $sandbox['current'], 10) as $field_config) {
    // Process only link fields.
    if ($field_config->get('field_type') === 'link') {
      $settings = $field_config->get('settings');
      if (!isset($settings['allowed_protocols'])) {
        // Add the new parameter with a default empty value.
        $settings['allowed_protocols'] = [];
        $field_config->set('settings', $settings);
        $field_config->save();
      }
    }
    $sandbox['current']++;
  }

  // Finish the batch.
  if ($sandbox['current'] < $total) {
    $sandbox['#finished'] = $sandbox['current'] / $total;
  }
  else {
    $sandbox['#finished'] = 1;
  }
}
