<?php

/**
 * @file
 * Install, update and uninstall functions for the field module.
 */

/**
 * Implements hook_update_last_removed().
 */
function field_update_last_removed(): int {
  return 8500;
}

/**
 * Update existing DecimalItem fields to match the new maximum value.
 */
function field_update_10001() {

  // Load all decimal field storage entities:
  $decimalFieldStorageEntities = \Drupal::entityTypeManager()->getStorage('field_storage_config')->loadByProperties([
    'type' => 'decimal',
  ]);

  foreach ($decimalFieldStorageEntities as $decimalFieldStorageEntity) {
    /** @var \Drupal\field\Entity\FieldStorageConfig $decimalFieldStorageEntity*/

    $precision = (int) ini_get('precision');
    $precisionMax = max($precision, 10);

    // Adjust the precision value, if it is higher, than the allowed
    // initial precision configuration option value:
    $precisionValue = (int) $decimalFieldStorageEntity->getSetting('precision');
    $newPrecisionValue = $precisionValue > $precisionMax ? $precisionMax : $precisionValue;

    // Adjust the scale value, if it is higher, than the allowed
    // initial precision configuration option value:
    $scaleValue = (int) $decimalFieldStorageEntity->getSetting('scale');
    $newScaleValue = $scaleValue > $precisionMax ? $precisionMax : $scaleValue;

    // Set the new precision and scale values if they changed:
    if ($precisionValue !== $newPrecisionValue || $scaleValue !== $newScaleValue) {
      $decimalFieldStorageEntity->setSetting('column_changes_handled', TRUE);
      $decimalFieldStorageEntity->setSetting('precision', $newPrecisionValue);
      $decimalFieldStorageEntity->setSetting('scale', $newScaleValue);
      // Update the field storage definition:
      \Drupal::service('entity.definition_update_manager')->updateFieldStorageDefinition($decimalFieldStorageEntity);
    }

  }
}
