<?php

declare(strict_types=1);

/**
 * @file
 * Install function for the Rest Test Views module.
 */

use Drupal\views\Tests\ViewTestData;

/**
 * Implements hook_install().
 */
function rest_test_views_install() {

  // Install the state and schema by for views test data.
  \Drupal::state()->set('views_test_data_schema', ViewTestData::schemaDefinition());
  \Drupal::state()->set('views_test_data_views_data', ViewTestData::viewsData());
  drupal_flush_all_caches();
}
