<?php

/**
 * @file
 * Hook implementations for layout_builder_form_block_test module.
 */

declare(strict_types=1);

/**
 * Implements hook_block_alter().
 */
function layout_builder_form_block_test_block_alter(&$definitions): void {
  // Allow a test block containing a form to be placed in navigation via layout
  // builder.
  $definitions['layout_builder_form_block_test_form_api_form_block']['allow_in_navigation'] = TRUE;
}
