<?php

use Drupal\Core\Render\Markup;

/**
 * Implements hook_library_info_alter().
 *
 * When this module is enabled, we want to replace the production build of a
 * JSX theme's app with a Vite script. This function does the first part of
 * that. jsx_vite_preprocess_html() does the second part.
 */
function dr_pepper_library_info_alter(&$libraries, $extension) {
  // @todo: Check if app is in dev mode
    // Remove the JS and CSS, but keep other info such as the dependencies.
    unset($libraries['app']['js']);
    unset($libraries['app']['css']);
}

/**
 * Implements hook_preprocess_html().
 */
function dr_pepper_preprocess_html(&$variables) {
  $snippet = <<<EOT
<script type="module">
  import RefreshRuntime from 'http://localhost:5173/@react-refresh'
  RefreshRuntime.injectIntoGlobalHook(window)
  window.$RefreshReg$ = () => {}
  window.$RefreshSig$ = () => (type) => type
  window.__vite_plugin_react_preamble_installed__ = true
</script>
<script type="module" src="http://localhost:5173/@vite/client"></script>
<script type="module" src="http://localhost:5173/src/main.tsx"></script>
EOT;
    if ($snippet) {
      $variables['page_bottom']['dr_pepper']['#markup'] = Markup::create($snippet);
    }
}
