<?php

/**
 * @file
 * Provides hook implementations for the Workflows module.
 */

declare(strict_types=1);

/**
 * Implements hook_field_widget_info_alter().
 */
function workflows_field_widget_info_alter(array &$info) {
  if (isset($info['options_select'])) {
    $info['options_select']['field_types'][] = 'workflow_state';
  }
}

/**
 * Implements hook_field_formatter_info_alter().
 */
function workflows_field_formatter_info_alter(array &$info) {
  if (isset($info['list_default'])) {
    $info['list_default']['field_types'][] = 'workflow_state';
  }
}
