<?php

/**
 * @file
 * Functions to support theming in the Stable9 theme.
 */

/**
 * Implements hook_preprocess_item_list__search_results().
 *
 * Converts the markup of #empty for search results.
 */
function stable9_preprocess_item_list__search_results(&$variables) {
  if (isset($variables['empty']['#tag'])) {
    $variables['empty']['#tag'] = 'h3';
  }
}

/**
 * Implements hook_preprocess_views_view().
 *
 * Adds BC classes that were previously added by the Views module.
 */
function stable9_preprocess_views_view(&$variables) {
  if (!empty($variables['attributes']['class'])) {
    $bc_classes = preg_replace('/[^a-zA-Z0-9- ]/', '-', $variables['attributes']['class']);
    $variables['attributes']['class'] = array_merge($variables['attributes']['class'], $bc_classes);
  }
  if (!empty($variables['css_class'])) {
    $existing_classes = explode(' ', $variables['css_class']);
    $bc_classes = preg_replace('/[^a-zA-Z0-9- ]/', '-', $existing_classes);
    $variables['css_class'] = implode(' ', array_merge($existing_classes, $bc_classes));
  }
}

/**
 * Prepares variables for views table templates.
 *
 * Default template: views-view-table.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - view: A ViewExecutable object.
 *   - rows: The raw row data.
 */
function template_preprocess_views_view_table(&$variables) {
  $view = $variables['view'];
  $options = $view->style_plugin->options;

  $fields = &$view->field;
  $columns = $handler->sanitizeColumns($options['columns'], $fields);

  foreach ($columns as $field => $column) {
    $variables['fields'][$field] = Html::cleanCssIdentifier($field);

    // Render the header labels.
    if ($field == $column && empty($fields[$field]->options['exclude'])) {
      // Add a CSS align class to each field if one was set.
      if (!empty($options['info'][$field]['align'])) {
        $variables['header'][$field]['attributes']->addClass(Html::cleanCssIdentifier($options['info'][$field]['align']));
      }
    }

    // Add a CSS align class to each field if one was set.
    if (!empty($options['info'][$field]['align'])) {
      $variables['fields'][$field] .= ' ' . Html::cleanCssIdentifier($options['info'][$field]['align']);
    }
  }
}
