<?php

/**
 * @file
 * Provides the API that allows renaming URLs.
 */

use Drupal\Core\Language\LanguageInterface;

/**
 * Implements hook_language_fallback_candidates_OPERATION_alter().
 */
function path_alias_language_fallback_candidates_path_alias_alter(array &$candidates, array $context): void {
  // Only fall back to LanguageInterface::LANGCODE_NOT_SPECIFIED.
  $candidates = array_intersect_key($candidates, [
    $context['langcode'] => 1,
    LanguageInterface::LANGCODE_NOT_SPECIFIED => 1,
  ]);
}
