<?php

/**
 * @file
 */

use Drupal\navigation\TopBarRegion;

/**
 * Implements hook_module_implements_alter().
 */
function navigation_module_implements_alter(&$implementations, $hook): void {
  if ($hook == 'page_top') {
    $group = $implementations['navigation'];
    unset($implementations['navigation']);
    $implementations['navigation'] = $group;
  }
  if ($hook == 'help') {
    // We take over the layout_builder hook_help().
    unset($implementations['layout_builder']);
  }
}

/**
 * Prepares variables for navigation top bar template.
 *
 * Default template: top-bar.html.twig
 *
 * @param $variables
 *   An associative array containing:
 *    - element: An associative array containing the properties and children of
 *      the top bar.
 */
function template_preprocess_top_bar(&$variables): void {
  $element = $variables['element'];

  foreach (TopBarRegion::cases() as $region) {
    $variables[$region->value] = $element[$region->value] ?? NULL;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function navigation_preprocess_menu_local_tasks__navigation(&$variables): void {
  $navigation_renderer = \Drupal::service('navigation.renderer');
  $variables['top_bar_tasks_exist'] = $navigation_renderer->hasLocalTasks();
}
