<?php

/**
 * @file
 * Contains functions for testing calling deprecated functions in tests.
 */

declare(strict_types=1);



/**
 * Implements hook_deprecated_hook().
 */
function deprecation_test_deprecated_hook($arg) {
  return $arg;
}

/**
 * Implements hook_deprecated_alter_alter().
 */
function deprecation_test_deprecated_alter_alter(&$data, $context1, $context2): void {
  $data = [$context1, $context2];
}
