core.menu.static_menu_link_overrides:
  type: config_object
  label: 'Static menu link overrides'
  constraints:
    FullyValidatable: ~
  mapping:
    definitions:
      type: sequence
      label: Definitions
      sequence:
        type: mapping
        label: Definition
        mapping:
          menu_name:
            type: string
            label: 'Menu name'
            constraints:
              NotNull: []
          parent:
            type: string
            label: 'Parent'
            constraints:
              NotNull: []
              PluginExists:
                manager: plugin.manager.menu.link
          weight:
            type: weight
            label: 'Weight'
          expanded:
            type: boolean
            label: 'Expanded'
          enabled:
            type: boolean
            label: 'Enabled'
