<?php

/**
 * @file
 * Install, update and uninstall functions for the system module.
 */

use Drupal\Component\Utility\Crypt;
use Drupal\Core\Link;
use Drupal\Core\StringTranslation\TranslatableMarkup;
use Drupal\Core\Update\EquivalentUpdate;
use Drupal\Core\Url;
use Drupal\Core\Utility\Error;
use Psr\Http\Client\ClientExceptionInterface;

// cspell:ignore quickedit

/**
 * An array of machine names of modules that were removed from Drupal core.
 */
const DRUPAL_CORE_REMOVED_MODULE_LIST = [
  'action' => 'Action UI',
  'book' => 'Book',
  'aggregator' => 'Aggregator',
  'ckeditor' => 'CKEditor',
  'color' => 'Color',
  'forum' => 'Forum',
  'hal' => 'HAL',
  'quickedit' => 'Quick Edit',
  'rdf' => 'RDF',
  'statistics' => 'Statistics',
  'tour' => 'Tour',
  'tracker' => 'Tracker',
];

/**
 * An array of machine names of themes that were removed from Drupal core.
 */
const DRUPAL_CORE_REMOVED_THEME_LIST = [
  'bartik' => 'Bartik',
  'classy' => 'Classy',
  'seven' => 'Seven',
  'stable' => 'Stable',
];

/**
 * Implements hook_install().
 */
function system_install(): void {
  // Populate the cron key state variable.
  $cron_key = Crypt::randomBytesBase64(55);
  \Drupal::state()->set('system.cron_key', $cron_key);

  // Populate the site UUID and default name (if not set).
  $site = \Drupal::configFactory()->getEditable('system.site');
  $site->set('uuid', \Drupal::service('uuid')->generate());
  if (!$site->get('name')) {
    $site->set('name', 'Drupal');
  }
  $site->save(TRUE);

  // Populate the dummy query string added to all CSS and JavaScript files.
  \Drupal::service('asset.query_string')->reset();
}

/**
 * Implements hook_schema().
 */
function system_schema(): array {
  // @deprecated The sequences table has been deprecated in drupal:10.2.0 and is
  // removed from drupal:12.0.0. See https://www.drupal.org/node/3220378.
  // @todo Remove sequences table in Drupal 12. See https://www.drupal.org/i/3335756
  $schema['sequences'] = [
    'description' => 'Stores IDs.',
    'fields' => [
      'value' => [
        'description' => 'The value of the sequence.',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ],
    ],
    'primary key' => ['value'],
  ];

  return $schema;
}

/**
 * Implements hook_update_last_removed().
 */
function system_update_last_removed(): int {
  return 10201;
}

/**
 * Invalidate container because the module handler has changed.
 */
function system_update_11100(): void {
  \Drupal::service('kernel')->invalidateContainer();
}

/**
 * Display requirements from security advisories.
 *
 * @param array[] $requirements
 *   The requirements array as specified in hook_requirements().
 */
function _system_advisories_requirements(array &$requirements): void {
  if (!\Drupal::config('system.advisories')->get('enabled')) {
    return;
  }

  /** @var \Drupal\system\SecurityAdvisories\SecurityAdvisoriesFetcher $fetcher */
  $fetcher = \Drupal::service('system.sa_fetcher');
  try {
    $advisories = $fetcher->getSecurityAdvisories(TRUE, 5);
  }
  catch (ClientExceptionInterface $exception) {
    $requirements['system_advisories']['title'] = t('Critical security announcements');
    $requirements['system_advisories']['severity'] = REQUIREMENT_WARNING;
    $requirements['system_advisories']['description'] = ['#theme' => 'system_security_advisories_fetch_error_message'];
    Error::logException(\Drupal::logger('system'), $exception, 'Failed to retrieve security advisory data.');
    return;
  }

  if (!empty($advisories)) {
    $advisory_links = [];
    $severity = REQUIREMENT_WARNING;
    foreach ($advisories as $advisory) {
      if (!$advisory->isPsa()) {
        $severity = REQUIREMENT_ERROR;
      }
      $advisory_links[] = new Link($advisory->getTitle(), Url::fromUri($advisory->getUrl()));
    }
    $requirements['system_advisories']['title'] = t('Critical security announcements');
    $requirements['system_advisories']['severity'] = $severity;
    $requirements['system_advisories']['description'] = [
      'list' => [
        '#theme' => 'item_list',
        '#items' => $advisory_links,
      ],
    ];
    if (\Drupal::moduleHandler()->moduleExists('help')) {
      $requirements['system_advisories']['description']['help_link'] = Link::createFromRoute(
        'What are critical security announcements?',
        'help.page', ['name' => 'system'],
        ['fragment' => 'security-advisories']
      )->toRenderable();
    }
  }
}

/**
 * Update length of menu_tree fields url and route_param_key from 255 to 2048.
 */
function system_update_11001(): void {
  $schema = \Drupal::database()->schema();
  $spec = [
    'description' => 'The external path this link points to (when not using a route).',
    'type' => 'varchar',
    'length' => 2048,
    'not null' => TRUE,
    'default' => '',
  ];
  $schema->changeField('menu_tree', 'url', 'url', $spec);

  $spec = [
    'description' => 'An encoded string of route parameters for loading by route.',
    'type' => 'varchar',
    'length' => 2048,
  ];
  $schema->changeField('menu_tree', 'route_param_key', 'route_param_key', $spec);
}

/**
 * Equivalent update to 10400.
 */
function system_update_11102(): TranslatableMarkup|null {
  // This is a no-op that exists to prevent an upgrade from 10.4+ to 11.0. That
  // path is actually a downgrade.
  $equivalent_update = \Drupal::service('update.update_hook_registry')
    ->getEquivalentUpdate();
  if ($equivalent_update instanceof EquivalentUpdate) {
    return $equivalent_update->toSkipMessage();
  }
  return NULL;
}
