<?php

/**
 * @file
 * Contains install and update functions for Migrate.
 */

use Drupal\Component\Render\FormattableMarkup;
use Drupal\migrate\MigrateUpdateHelper;

/**
 * Implements hook_update_last_removed().
 */
function migrate_update_last_removed(): int {
  return 10100;
}

/**
 * Copy values from legacy migration map and message tables to new ones.
 */
function migrate_update_10101(&$sandbox): ?FormattableMarkup {
  return \Drupal::classResolver(MigrateUpdateHelper::class)->updateMapAndMessageTables($sandbox);
}
