<?php

/**
 * @file
 * Contains main module functions.
 */

declare(strict_types=1);

use Drupal\Component\Utility\Html;

/**
 * Implements hook_preprocess_HOOK().
 */
function navigation_test_preprocess_block__navigation(&$variables) {
  // Add some additional classes so we can target the correct contextual link
  // in tests.
  $variables['attributes']['class'][] = Html::cleanCssIdentifier('block-' . $variables['elements']['#plugin_id']);
}

/**
 * Implements hook_navigation_content_top().
 */
function navigation_test_navigation_content_top(): array {
  if (\Drupal::state()->get('navigation_content_top')) {
    return [
      'navigation_foo' => [
        '#markup' => 'foo',
      ],
      'navigation_bar' => [
        '#markup' => 'bar',
      ],
      'navigation_baz' => [
        '#markup' => 'baz',
      ],
    ];
  }
  else {
    return [];
  }
}

/**
 * Implements hook_navigation_content_top_alter().
 */
function navigation_test_navigation_content_top_alter(&$promoted): void {
  if (\Drupal::state()->get('navigation_content_top_alter')) {
    unset($promoted['navigation_foo']);
    $promoted['navigation_bar']['#markup'] = 'new bar';
    $promoted['navigation_baz']['#weight'] = '-100';
  }
}
