<?php

/**
 * @file
 * Install, update, and uninstall functions for the Views Test module.
 */

use Drupal\views\Tests\ViewTestData;

/**
 * Implements hook_schema().
 */
function views_test_data_schema() {
  $schema = \Drupal::state()->get('views_test_data_schema');
  if (empty($schema)) {
    $schema = ViewTestData::schemaDefinition();
  }
  return $schema;
}

/**
 * Implements hook_install().
 */
function views_test_data_install() {
  // Add the marquee tag to possible html elements to test the field handler.
  $values = [
    'div' => 'DIV',
    'span' => 'SPAN',
    'h1' => 'H1',
    'h2' => 'H2',
    'h3' => 'H3',
    'h4' => 'H4',
    'h5' => 'H5',
    'h6' => 'H6',
    'p' => 'P',
    'strong' => 'STRONG',
    'em' => 'EM',
    'marquee' => 'MARQUEE',
  ];
  \Drupal::configFactory()->getEditable('views.settings')->set('field_rewrite_elements', $values)->save();

  // Install the state and schema by default.
  \Drupal::state()->set('views_test_data_schema', ViewTestData::schemaDefinition());
  \Drupal::state()->set('views_test_data_views_data', ViewTestData::viewsData());
  drupal_flush_all_caches();
}
