<?php

namespace Drupal\Composer\Plugin\Scaffold;

/**
 * Produces code for the DrupalLocation file.
 *
 * To ensure the project's codebase is portable, the generated code must not
 * use absolute paths. It should instead use the __DIR__ constant, which in the
 * generated class will give the project root.
 *
 * @internal
 */
class LocationsClassTemplate {

  /**
   * The template code for the DrupalLocation class file which is written.
   *
   * This contains the token '%app_root' which is replaced when the file is
   * written.
   *
   * @var string
   */
  private static $generatedFileTemplate = <<<'EOF'
    <?php

    namespace Drupal\Locations;

    /**
     * Defines the Drupal app root.
     *
     * This allows Drupal to find the directory in which Drupal files are
     * located, such as Drupal core, the sites directory, and the extension
     * directories.
     *
     * This is defined in a class so it is available as soon as the Composer
     * autoloader has been included.
     *
     * This class must be declared in the 'autoload' section of the project
     * root's composer.json file.
     *
     * See the README in the drupal/core-composer-scaffold package for more
     * details.
     *
     * This file was generated by
     * \Drupal\Composer\Plugin\Scaffold\ManageDrupalLocations.
     */
    class DrupalLocation {

      /**
       * Defines the root directory of the Drupal installation.
       *
       * This is the directory containing the scaffolded index.php file which is
       * Drupal's web entry point.
       */
      public const APP_ROOT = __DIR__ . '%app_root';

    }

    EOF;

  /**
   * Gets the code for the locations class.
   *
   * @param string $relative_app_root
   *   The relative path to the Drupal app root, relative to the Composer
   *   project root, with an initial slash, and without a trailing slash.
   *
   * @return string
   *   The PHP code to write to the Drupal locations class.
   */
  public static function getLocationsClassCode(string $relative_app_root): string {
    $class_php = str_replace('%app_root', $relative_app_root, static::$generatedFileTemplate);
    return $class_php;
  }

}
