<?php

/**
 * @file
 * Functions to support theming.
 */

/**
 * Implements THEME_page_attachments_alter().
 */
function starterkit_theme_page_attachments_alter(&$page) {
  // Pass a value to our JS behavior (e.g. Drupal.behaviors.readingTime).
  $page['#attached']['drupalSettings']['starterkit_theme']['wordsPerMinute'] = 225;
  // Attach our JS behavior to every page.
  $page['#attached']['library'][] = 'starterkit_theme/reading-time';
}

/**
 * Implements hook_preprocess_image_widget().
 */
function starterkit_theme_preprocess_image_widget(array &$variables): void {
  $data = &$variables['data'];

  // This prevents image widget templates from rendering preview container HTML
  // to users that do not have permission to access these previews.
  // @todo revisit in https://drupal.org/node/953034
  // @todo revisit in https://drupal.org/node/3114318
  if (isset($data['preview']['#access']) && $data['preview']['#access'] === FALSE) {
    unset($data['preview']);
  }
}
