<?php

/**
 * @file
 * Mock module for path alias language fallback tests.
 */

declare(strict_types=1);

use Drupal\Core\Database\Query\AlterableInterface;

/**
 * Implements hook_language_fallback_candidates_OPERATION_alter().
 */
function path_alias_language_fallback_test_language_fallback_candidates_path_alias_alter(array &$candidates, array $context): void {
  $fallback_language = \Drupal::state()
    ->get('path_alias_language_fallback_test.fallback_path_alias_alter.candidates');
  if ($fallback_language) {
    array_unshift($candidates, $fallback_language);
  }
}

/**
 * Implements hook_query_TAG_alter().
 */
function path_alias_language_fallback_test_query_path_alias_language_fallback_alter(AlterableInterface $query): void {
  /** @var \Drupal\Core\Database\Query\SelectInterface $query */
  // Replace the existing language code ordering.
  $fields = &$query->getOrderBy();
  unset($fields['base_table.langcode']);

  // Sort results according to the order of the language fallback chain, which
  // can be found in the values of the langcode condition.
  $conditions = &$query->conditions();
  foreach ($conditions as $condition) {
    if (is_array($condition) && isset($condition['field']) && $condition['field'] === 'base_table.langcode') {
      $order = '(CASE ';
      foreach (array_values($condition['value']) as $index => $lang) {
        $order .= "WHEN base_table.langcode = '$lang' THEN $index ";
      }
      $order .= 'END)';
      $order_alias = $query->addExpression($order, 'order');
      $fields = [$order_alias => 'ASC'] + $fields;
      break;
    }
  }
}
