<?php

/**
 * @file
 * Helper module for the CKEditor5 tests.
 */

declare(strict_types=1);

/**
 * Implements hook_entity_bundle_info_alter().
 */
function ckeditor5_test_entity_bundle_info_alter(&$bundles): void {
  if (isset($bundles['taxonomy_term'])) {
    foreach ($bundles['taxonomy_term'] as $key => $bundle) {
      $bundles['taxonomy_term'][$key]['ckeditor5_link_suggestions'] = TRUE;
    }
  }

  if (isset($bundles['media'])) {
    foreach ($bundles['media'] as $key => $bundle) {
      $bundles['media'][$key]['ckeditor5_link_suggestions'] = TRUE;
    }
  }
}
