<?php

/**
 * @file
 * Install, update and uninstall functions for the block_content module.
 */

use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_update_last_removed().
 */
function block_content_update_last_removed() {
  return 10300;
}

/**
 * Install the owner field for Block Content entities.
 */
function block_content_update_10301(): void {
  $entityDefinitionUpdateManager = \Drupal::entityDefinitionUpdateManager();
  $entityType = $entityDefinitionUpdateManager->getEntityType('block_content');

  $storage_definition = BaseFieldDefinition::create('entity_reference')
    ->setLabel(new TranslatableMarkup('User ID'))
    ->setSetting('target_type', 'user')
    ->setTranslatable($entityType->isTranslatable());
  $entityDefinitionUpdateManager
    ->installFieldStorageDefinition('uid', 'block_content', 'block_content', $storage_definition);
}
