<?php

/**
 * @file
 * Helper module for jQuery 3.6 FunctionalJavascript test compatibility.
 */

declare(strict_types=1);

/**
 * Implements hook_library_info_alter().
 */
function jquery_keyevent_polyfill_test_library_info_alter(&$libraries, $module) {
  if ($module == 'core' && isset($libraries['jquery'])) {
    $libraries['jquery']['js']['modules/system/tests/modules/jquery_keyevent_polyfill_test/js/jquery.keyevent.polyfill.js'] = [];
  }
}
