<?php

/**
 * @file
 * The MongoDB module provides the connection between Drupal and a MongoDB database.
 */

use Drupal\Core\Database\Database;
use Drupal\Core\Database\Query\AlterableInterface;
use Drupal\Core\Database\Query\ConditionInterface;
use Drupal\Core\Database\Query\SelectInterface;

/**
 * Implements hook_entity_type_alter().
 */
function mongodb_entity_type_alter(array &$entity_types) {
  $connection = NULL;
  if (Database::getConnectionInfo()) {
    $connection = Database::getConnection();
  }

  if ($connection && $connection->driver() == 'mongodb') {
    if (!empty($entity_types['content_moderation_state'])) {
      $entity_types['content_moderation_state']->setHandlerClass('storage_schema', 'Drupal\mongodb\modules\content_moderation\ContentModerationStateStorageSchema');
    }

    if (!empty($entity_types['node'])) {
      $entity_types['node']->setStorageClass('Drupal\mongodb\modules\node\NodeStorage');
    }

    if (!empty($entity_types['user'])) {
      $entity_types['user']->setStorageClass('Drupal\mongodb\modules\user\UserStorage');
    }

    if (!empty($entity_types['view'])) {
      $entity_types['view']->setStorageClass('Drupal\mongodb\modules\views\ViewStorage');
      $entity_types['view']->setClass('Drupal\mongodb\modules\views\View');
    }
  }
}

/**
 * Implements hook_field_info_alter().
 */
function mongodb_field_info_alter(array &$info) {
  if (isset($info['boolean']['class'])) {
    $info['boolean']['class'] = 'Drupal\mongodb\Plugin\Field\FieldType\BooleanItem';
    $info['boolean']['provider'] = 'mongodb';
  }
  if (isset($info['changed']['class'])) {
    $info['changed']['class'] = 'Drupal\mongodb\Plugin\Field\FieldType\ChangedItem';
    $info['changed']['provider'] = 'mongodb';
  }
  if (isset($info['created']['class'])) {
    $info['created']['class'] = 'Drupal\mongodb\Plugin\Field\FieldType\CreatedItem';
    $info['created']['provider'] = 'mongodb';
  }
  if (isset($info['timestamp']['class'])) {
    $info['timestamp']['class'] = 'Drupal\mongodb\Plugin\Field\FieldType\TimestampItem';
    $info['timestamp']['provider'] = 'mongodb';
  }
}

/**
 * Implements hook_search_plugin_alter().
 */
function mongodb_search_plugin_alter(array &$definitions) {
  if (isset($definitions['help_search'])) {
    $definitions['help_search']['class'] = 'Drupal\mongodb\Plugin\Search\HelpSearch';
    $definitions['help_search']['provider'] = 'mongodb';
  }
  if (isset($definitions['node_search'])) {
    $definitions['node_search']['class'] = 'Drupal\mongodb\Plugin\Search\NodeSearch';
    $definitions['node_search']['provider'] = 'mongodb';
  }
  if (isset($definitions['user_search'])) {
    $definitions['user_search']['class'] = 'Drupal\mongodb\Plugin\Search\UserSearch';
    $definitions['user_search']['provider'] = 'mongodb';
  }
}

/**
 * Implements hook_query_TAG_alter().
 */
function mongodb_query_entity_reference_alter(AlterableInterface $query) {
  // Overrides for the module content_moderation.
  if (\Drupal::moduleHandler()->moduleExists('block_content')) {
    if ($query instanceof SelectInterface && $query->getMetaData('entity_type') === 'block_content' && $query->hasTag('block_content_access')) {
      if (!_mongodb_block_content_has_reusable_condition($query->conditions(), $query->getTables())) {
        $query->condition('block_content_current_revision.reusable', TRUE);
      }
    }
  }
}

/**
 * Utility function is the MongoDB version of _block_content_has_reusable_condition.
 */
function _mongodb_block_content_has_reusable_condition(array $condition, array $tables) {
  // If this is a condition group call this function recursively for each nested
  // condition until a condition is found that return TRUE.
  if (isset($condition['#conjunction'])) {
    foreach (array_filter($condition, 'is_array') as $nested_condition) {
      if (_mongodb_block_content_has_reusable_condition($nested_condition, $tables)) {
        return TRUE;
      }
    }
    return FALSE;
  }
  if (isset($condition['field'])) {
    $field = $condition['field'];
    if (is_object($field) && $field instanceof ConditionInterface) {
      return _mongodb_block_content_has_reusable_condition($field->conditions(), $tables);
    }
    $base_table = \Drupal::entityTypeManager()->getDefinition('block_content')->getBaseTable();
    foreach ($tables as $table) {
      if ($table['table'] === $base_table && $field === 'block_content_current_revision.reusable') {
        return TRUE;
      }
    }
  }
  return FALSE;
}
